openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  description: |-
    This is a sample Pet Store Server based on the OpenAPI 3.0 specification.  You can find out more about
    Swagger at [https://swagger.io](https://swagger.io). In the third iteration of the pet store, we've switched to the design first approach!
    You can now help us improve the API whether it's by making changes to the definition itself or to the code.
    That way, with time, we can improve the API in general, and expose some of the new features in OAS3.

    _If you're looking for the Swagger 2.0/OAS 2.0 version of Petstore, then click [here](https://editor.swagger.io/?url=https://petstore.swagger.io/v2/swagger.yaml). Alternatively, you can load via the `Edit > Load Petstore OAS 2.0` menu option!_
    
    Some useful links:
    - [The Pet Store repository](https://github.com/swagger-api/swagger-petstore)
    - [The source API definition for the Pet Store](https://github.com/swagger-api/swagger-petstore/blob/master/src/main/resources/openapi.yaml)
  version: 0.1 alpha
# servers:
  # - url: https://petstore3.swagger.io/api/v3
tags:
  - name: market
    description: Market API
  - name: announcement
    description: Announcement's system API
  - name: community
    description: Community system API. Create and develop your own community.
paths:
  /market:
    get:
      tags:
        - market
      summary: Get all adverts from market
      description: Returns advert's list to user
      operationId: getAdverts
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '401':
          description: Auth is required
        '500':
          description: Internal server error
  /market/{advertId}:
    get:
      tags:
        - market
      summary: Find advert by ID
      description: Returns a single advert
      operationId: getAdvertById
      parameters:
        - name: advertId
          in: path
          description: ID of advert to return
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
        '400':
          description: Invalid ID supplied
        '404':
          description: Pet not found
        '500':
          description: Internal server error